# Generated by Django 5.2.6 on 2025-10-16 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_jobpost_jobapplication_delete_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='salary',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
