# Generated by Django 5.2.6 on 2025-10-16 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_jobpost_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='salary',
            field=models.CharField(blank=True, null=True),
        ),
    ]
