# Generated by Django 5.2.6 on 2025-11-13 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_companyprofile_peoples'),
        ('jobs', '0008_jobapplication_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_logo', to='account.companyprofile'),
        ),
    ]
