# Generated by Django 5.2.6 on 2025-10-14 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_eventreaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventreaction',
            old_name='is_like',
            new_name='like',
        ),
    ]
