# Generated by Django 5.2.6 on 2025-10-14 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_rename_is_like_eventreaction_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventreaction',
            name='like',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
