# Generated by Django 5.2.6 on 2025-09-17 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_pendinguser_role_user_role_companyprofile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pendinguser',
            old_name='full_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='full_name',
            new_name='name',
        ),
    ]
