# Generated by Django 5.2.6 on 2025-09-18 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_rename_full_name_pendinguser_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='department',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
