# Generated by Django 5.2.6 on 2025-10-28 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
