# Generated by Django 5.2.6 on 2025-10-28 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_employerprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='cover_picture',
            field=models.ImageField(blank=True, null=True, upload_to='cover_pics/'),
        ),
    ]
