# Generated by Django 5.2.6 on 2025-10-28 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_jobseekerprofile_cover_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='education',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
