# Generated by Django 5.2.6 on 2025-10-29 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_jobseekerprofile_bio_jobseekerprofile_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='cover_picture',
            field=models.ImageField(blank=True, null=True, upload_to='cover_pics/'),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='education',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
