# Generated by Django 5.2.6 on 2025-10-29 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_employerprofile_bio_employerprofile_cover_picture_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyprofile',
            old_name='description',
            new_name='bio',
        ),
        migrations.RenameField(
            model_name='employerprofile',
            old_name='education',
            new_name='qualification',
        ),
        migrations.RenameField(
            model_name='jobseekerprofile',
            old_name='education',
            new_name='location',
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='cover_picture',
            field=models.ImageField(blank=True, null=True, upload_to='cover_pics/'),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='courses',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='projects',
            field=models.TextField(blank=True, null=True),
        ),
    ]
