# Generated by Django 5.2.6 on 2025-10-29 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_rename_description_companyprofile_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
