# Generated by Django 5.2.6 on 2025-11-06 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='peoples',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
